version: '2'
services:
  web:
    build: ./docker/nginx
    ports:
        - "8080:80"
    volumes:
        - .:/var/www/app
        - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
    build: ./docker/php
    volumes:
        - .:/var/www/app
