imports:
    - resource: ../vendor/ql/mcp-panthor/configuration/panthor-slim.yml
    - resource: ../vendor/ql/mcp-panthor/configuration/panthor.yml
    - resource: di.yml
    - resource: routes.yml

parameters:

    table_of_contents:
        hello_world:    ['Hello World!', 'src/TestPageController.php']
        twig_example:   ['Twig Example', 'src/TwigController.php']
        errors:         ['Test Error Handling', 'src/ErrorTestingController.php']
        api_example:    ['API Example', 'src/APIController.php']
        api_problem:    ['API Problem', 'src/APIProblemController.php']
