parameters:
    routes:
        hello_world:
            route: '/'
            stack: ['page.hello_world']

        twig_example:
            route: '/twig'
            stack: ['page.twig']

        errors:
            route: '/error'
            stack: ['page.errors']
