parameters:
    routes:
        hello_world:
            route: '/'
            stack: ['page.hello_world']

        twig_example:
            route: '/twig'
            stack: ['page.twig']

        errors:
            route: '/error'
            stack: ['page.errors']

        api_example:
            route: '/api-example'
            stack: ['api.example']

        api_problem:
            route: '/api-problem'
            stack: ['api.problem']
